# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 492258f5e1c3e453e3a64902ef12d5bba2b035a601464d7892643e5109448611eb68a61d7e6f40b529e4bbc9b584aecd3a24c3090198707181f7ec8a709a3869

test:
  secret_key_base: fb1d413cf1c853b2513843bb571fa5276c12f2388c2fdbae1a9d10b57afede995ae0a42006e66e3fa8655fe82ea6046d8613c1acd0e9e030c55fc238279914b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
