# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13a8660180a556c8eb7b6e0795cbe8ae0b7f199185234946cd529f7fb0354c9792ee51a53c5e49da289ae9257f1f7ac78b5c14a776465f104f859812dc623f1c

test:
  secret_key_base: 8519af27d2e41d5654054e1130c1f45089e80c0c39babf45aaa8410c5c126d2fa0c83fa144b49479198701c41ddc4054af0ba8cf1886450d34c5729dd021ffde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
